name: Deploy Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Placeholder step
        run: echo "CI/CD pipeline initialized. Terraform/Ansible steps will be added next."
