- name: Set up Terraform
  uses: hashicorp/setup-terraform@v2

- name: Terraform Init
  run: terraform init
  working-directory: ./terraform

- name: Terraform Apply
  run: |
    terraform apply -auto-approve \
      -var="hcloud_token=${{ secrets.HETZNER_TOKEN }}" \
      -var="ssh_public_key=${{ secrets.PUBLIC_SSH_KEY }}"
  working-directory: ./terraform

- name: Extract IP
  id: tf_output
  run: |
    echo "SERVER_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
  working-directory: ./terraform
