name: Deploy to Hetzner

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="hcloud_token=${{ secrets.HETZNER_TOKEN }}" \
            -var="ssh_public_key=${{ secrets.PUBLIC_SSH_KEY }}" \
            -var="ssh_key_name=${{ secrets.SSH_KEY_NAME }}"
        working-directory: ./terraform

      - name: Extract Hetzner IP
        id: get_ip
        run: echo "SERVER_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV
        working-directory: ./terraform


      - name: Write SSH key to file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Ansible
        run: |
          echo "[vps]" > ansible/inventory.ini
          echo "${{ env.SERVER_IP }} ansible_user=root ansible_ssh_private_key_file=./key.pem" >> ansible/inventory.ini

          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml

